spring:
  application:
    name: spring_email

  mail:
    host: smtp.gmail.com
    port: 587
    username: glenbabla@gmail.com
    password: pidy qryr olhr eotb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true